name: Build

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build @golderbrother/core
        run: npm run build
        working-directory: ./packages/core

      - name: Upload @golderbrother/core dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: golderbrother-core-dist
          path: packages/core/dist/

      - name: Build @golderbrother/package1
        run: npm run build
        working-directory: ./packages/package1

      - name: Upload @golderbrother/package1 dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: golderbrother-package1-dist
          path: packages/package1/dist/

      - name: Build @golderbrother/package2
        run: npm run build
        working-directory: ./packages/package2

      - name: Upload @golderbrother/package2 dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: golderbrother-package2-dist
          path: packages/package2/dist/
