name: deployment
on:
  push:
    branches:
      - master
jobs:
  deployment:
    name: Deploy 执行流程
    # 后期加测试脚本时再用
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    environment: release
    steps:
      # Step1
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
          fetch-depth: 0
          node-version: 16.x
          cache: pnpm
      # Step2
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x
          store-path: ~/.pnpm-store
      # Step3
      - name: 缓存依赖
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      # Step4
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      # Step5
      - name: 代码校验
        run: npm run lint
      # Step6
      - name: 单元测试
        run: npm run test
      # Step7
      - name: 文档构建
        run: npm run docs:build
      # Step8 代码构建 & 发布
      - name: 发布npm(代码构建 & 发布)
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore: publish packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
